# Generated by Django 3.2.4 on 2021-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quizTaken',
            field=models.IntegerField(default=0),
        ),
    ]
