# Generated by Django 3.2.4 on 2021-07-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_quiztaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
