# Generated by Django 3.2.4 on 2021-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
